#!/usr/bin/env python3
"""Build the Study-3 summary (tables + figure) from every per-adaptation CSV on disk.

Reads only committed result artifacts:
  results/tables/study3_{mode}_{adaptation}.csv
  results/tables/claim_gate_s3_{adaptation}.json
  results/tables/confirmatory_v2.csv            (Study-2 full fine-tune, archive reference)
and writes:
  results/tables/study3_{mode}_all.csv
  results/tables/STUDY3_RESULTS.md, STUDY3_RESULTS.md, paper/RESULTS_STUDY3.md
  figures/{mode}_study3_adaptations.png
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from pathlib import Path

PKG = Path(__file__).resolve().parents[1]
TABLES = PKG / "results" / "tables"

ADAPTATIONS = [
    ("zero_shot", "primary"),
    ("probe", "primary"),
    ("low_lr_ft", "secondary"),
]
METHODS = [("scratch", "Scratch"), ("mml_direct", "MML-direct"), ("lmop_jepa", "LMOP-JEPA")]
DEFAULT_PRETRAIN_RUN = "confirmatory_s2_v2_20260926T162730Z"

# Audit findings that cannot be derived from the CSVs themselves (see RESEARCH_AUDIT.md).
ADAPTATION_NOTES = {
    "zero_shot": (
        "EXPLORATORY / POST-HOC. Amendment 0004 was written after these exact zero-shot numbers "
        "were observed (they are quoted in its problem statement), and no fine-tuning occurs, so "
        "MML/LMOP predictions are identical across seeds and N: the across-seed CI has zero width "
        "and cannot support a claim. Zero-shot error is also worse than Scratch trained on N=25 labels."
    ),
    "probe": "Primary protocol under amendment 0004; LMOP checkpoint retrained with the amended loss weights.",
    "low_lr_ft": "Secondary protocol under amendment 0004; same checkpoints as probe.",
    "full_ft_study2": "Archive: Study-2 freeze-then-unfreeze fine-tune (amendment 0003 LMOP recipe).",
}


def _mean(xs: list[float]) -> float:
    return sum(xs) / len(xs) if xs else float("nan")


def _std(xs: list[float]) -> float:
    if len(xs) < 2:
        return 0.0
    m = _mean(xs)
    return math.sqrt(sum((x - m) ** 2 for x in xs) / (len(xs) - 1))


def _load_csv(path: Path) -> list[dict]:
    with path.open() as f:
        return list(csv.DictReader(f))


def _lmop_provenance(gate: dict | None, pretrain_run: str) -> str:
    candidates = []
    if gate and gate.get("run_root"):
        candidates.append(Path(gate["run_root"]).parent / "pretrain_lmop" / "metrics.json")
    candidates.append(PKG / "runs" / pretrain_run / "pretrain_lmop" / "metrics.json")
    for path in candidates:
        if not path.exists():
            continue
        meta = json.loads(path.read_text())
        run = path.parent.parent.name
        if "lambda_var" in meta:
            return f"`{run}` (λ_var={meta['lambda_var']:g}, λ_u={meta['lambda_u']:g})"
        if meta.get("amendment") == "0003_matched_block_jepa":
            return f"`{run}` (λ_var=25, λ_u=0.1; amendment 0003 recipe)"
        return f"`{run}`"
    return "unknown"


def _cells(rows: list[dict], subsets: list[int]) -> list[dict]:
    out = []
    for n in subsets:
        for dist in ("id", "ood"):
            cell = {"n": n, "dist": dist}
            for method, _ in METHODS:
                vals = [
                    float(r["relative_l2"])
                    for r in rows
                    if r["method"] == method and int(r["real_label_budget"]) == n and r["distribution"] == dist
                ]
                cell[method] = (_mean(vals), _std(vals), len(vals))
            out.append(cell)
    return out


def summarize_study3(mode: str = "confirmatory", pretrain_run: str = DEFAULT_PRETRAIN_RUN) -> Path:
    subsets = [25, 100] if mode == "confirmatory" else [16, 32]
    groups: list[tuple[str, str, list[dict], dict | None]] = []
    all_rows: list[dict] = []
    for adaptation, role in ADAPTATIONS:
        path = TABLES / f"study3_{mode}_{adaptation}.csv"
        if not path.exists():
            groups.append((adaptation, role, [], None))
            continue
        rows = _load_csv(path)
        gate_path = TABLES / f"claim_gate_s3_{adaptation}.json"
        gate = json.loads(gate_path.read_text()) if gate_path.exists() else None
        groups.append((adaptation, role, rows, gate))
        all_rows.extend(rows)

    archive_path = TABLES / ("confirmatory_v2.csv" if mode == "confirmatory" else "smoke_v2_metrics.csv")
    archive_rows = _load_csv(archive_path) if archive_path.exists() else []

    if all_rows:
        fields = list(all_rows[0].keys())
        with (TABLES / f"study3_{mode}_all.csv").open("w", newline="") as f:
            w = csv.DictWriter(f, fieldnames=fields)
            w.writeheader()
            w.writerows(all_rows)

    lines = [
        "# Study-3 results (amendment 0004)",
        "",
        "Auto-generated by `scripts/summarize_study3.py` from `results/tables/study3_*` and "
        "`claim_gate_s3_*`. Relative L2 on genuine test sets, mean ± sample std over seeds {11, 23, 47}.",
        "",
    ]
    for adaptation, role, rows, gate in groups:
        lines.append(f"## {adaptation} ({role})")
        lines.append("")
        if not rows:
            lines.append("**NOT RUN** — no result CSV on disk.")
            lines.append("")
            continue
        expected = len(subsets) * 2 * len(METHODS) * (3 if mode == "confirmatory" else 1)
        verdict = gate["verdict"] if gate else "NO_GATE"
        lines.append(f"- Verdict (frozen gate, audited logic): `{verdict}`")
        lines.append(f"- Rows: {len(rows)}/{expected}")
        lines.append(f"- LMOP checkpoint: {_lmop_provenance(gate, pretrain_run)}")
        if gate:
            lines.append(f"- Run: `{Path(gate['run_root']).parent.name}` · git `{gate.get('git_sha')}`")
        lines.append(f"- Note: {ADAPTATION_NOTES[adaptation]}")
        lines.append("")
        lines.append("| N | Dist | Scratch | MML-direct | LMOP-JEPA | Δ(LMOP−MML) |")
        lines.append("|---|------|---------|------------|-----------|-------------|")
        for c in _cells(rows, subsets):
            s, m, l = c["scratch"], c["mml_direct"], c["lmop_jepa"]
            lines.append(
                f"| {c['n']} | {c['dist']} | {s[0]:.4f}±{s[1]:.4f} | {m[0]:.4f}±{m[1]:.4f} | "
                f"{l[0]:.4f}±{l[1]:.4f} | {l[0] - m[0]:+.4f} |"
            )
        lines.append("")

    if archive_rows:
        lines.append("## full_ft_study2 (archive reference)")
        lines.append("")
        lines.append(f"- Source: `results/tables/{archive_path.name}` · gate `claim_gate_v2.md`")
        lines.append(f"- Note: {ADAPTATION_NOTES['full_ft_study2']}")
        lines.append("")
        lines.append("| N | Dist | Scratch | MML-direct | LMOP-JEPA | Δ(LMOP−MML) |")
        lines.append("|---|------|---------|------------|-----------|-------------|")
        for c in _cells(archive_rows, subsets):
            s, m, l = c["scratch"], c["mml_direct"], c["lmop_jepa"]
            lines.append(
                f"| {c['n']} | {c['dist']} | {s[0]:.4f}±{s[1]:.4f} | {m[0]:.4f}±{m[1]:.4f} | "
                f"{l[0]:.4f}±{l[1]:.4f} | {l[0] - m[0]:+.4f} |"
            )
        lines.append("")

    fig_path = _figure(mode, groups, archive_rows, subsets)
    if fig_path is not None:
        lines.append(f"Figure: `{fig_path.relative_to(PKG)}`")
        lines.append("")

    floor_path = TABLES / "audit_positional_floor.json"
    if mode == "confirmatory" and floor_path.exists():
        floor = json.loads(floor_path.read_text())["splits"]
        lines.append("## Trivial-baseline audit (see RESEARCH_AUDIT.md)")
        lines.append("")
        lines.append(
            "Every trained model above is worse than the input-blind train-mean field. The downstream "
            "FNO has no coordinate channels, so it cannot localize the Dirichlet boundary "
            "(`results/tables/audit_positional_floor.json`)."
        )
        lines.append("")
        lines.append("| Dist | Train-mean field | Best spatially-constant output | Trained models (range, N=100 s11) |")
        lines.append("|------|------------------|--------------------------------|-----------------------------------|")
        for dist in ("id", "ood"):
            b = floor[dist]["baselines_rel_l2_mean"]
            vals = [m["rel_l2_mean"] for m in floor[dist]["models"].values()]
            lines.append(
                f"| {dist} | {b['train_mean_field']:.4f} | {b['per_example_best_constant']:.4f} | "
                f"{min(vals):.4f}–{max(vals):.4f} |"
            )
        lines.append("")
        base_fig = _baseline_figure(floor)
        if base_fig is not None:
            lines.append(f"Figure: `{base_fig.relative_to(PKG)}`")
            lines.append("")

    text = "\n".join(lines)
    out = TABLES / "STUDY3_RESULTS.md"
    for path in (out, PKG / "STUDY3_RESULTS.md", PKG / "paper" / "RESULTS_STUDY3.md"):
        path.write_text(text)
    return out


def _figure(mode: str, groups, archive_rows: list[dict], subsets: list[int]) -> Path | None:
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        return None

    panels = [(a, rows) for a, _, rows, _ in groups if rows]
    if archive_rows:
        panels.append(("full_ft_study2", archive_rows))
    if not panels:
        return None

    fig, axes = plt.subplots(2, len(panels), figsize=(3.2 * len(panels), 6.0), squeeze=False)
    colors = {"scratch": "#888888", "mml_direct": "#1f77b4", "lmop_jepa": "#d62728"}
    width = 0.26
    for col, (name, rows) in enumerate(panels):
        cells = _cells(rows, subsets)
        for row, dist in enumerate(("id", "ood")):
            ax = axes[row][col]
            sub = [c for c in cells if c["dist"] == dist]
            for k, (method, label) in enumerate(METHODS):
                xs = [i + (k - 1) * width for i in range(len(sub))]
                ys = [c[method][0] for c in sub]
                es = [c[method][1] for c in sub]
                ax.bar(xs, ys, width, yerr=es, capsize=2, color=colors[method], label=label)
            ax.set_xticks(range(len(sub)))
            ax.set_xticklabels([f"N={c['n']}" for c in sub])
            ax.set_title(f"{name} · {dist.upper()}", fontsize=9)
            if col == 0:
                ax.set_ylabel("Relative $L_2$ error (dimensionless)")
            if name == "zero_shot":
                ax.set_yscale("log")
            else:
                lo = min(c[m][0] - c[m][1] for c in sub for m, _ in METHODS)
                hi = max(c[m][0] + c[m][1] for c in sub for m, _ in METHODS)
                pad = 0.1 * (hi - lo + 1e-6)
                ax.set_ylim(lo - pad, hi + pad)
            ax.grid(True, axis="y", alpha=0.3)
    axes[0][0].legend(fontsize=7, loc="best")
    fig.suptitle("LMOP-JEPA Study-3: adaptation protocols (mean ± std over 3 seeds; lower is better)", fontsize=10)
    fig.tight_layout()
    out = PKG / "figures" / f"{mode}_study3_adaptations.png"
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, dpi=140)
    plt.close(fig)
    return out


def _baseline_figure(floor: dict) -> Path | None:
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        return None

    fig, axes = plt.subplots(1, 2, figsize=(10, 3.8), sharey=True)
    for ax, dist in zip(axes, ("id", "ood")):
        b = floor[dist]["baselines_rel_l2_mean"]
        labels = ["train-mean field", "best constant"]
        vals = [b["train_mean_field"], b["per_example_best_constant"]]
        colors = ["#2ca02c", "#bcbd22"]
        for tag, m in floor[dist]["models"].items():
            labels.append(tag.replace("_n100_s11", "").replace("_", " "))
            vals.append(m["rel_l2_mean"])
            colors.append("#d62728" if "lmop" in tag else "#1f77b4" if "mml" in tag else "#888888")
        ax.barh(range(len(vals)), vals, color=colors)
        ax.set_yticks(range(len(vals)))
        ax.set_yticklabels(labels, fontsize=8)
        ax.invert_yaxis()
        ax.set_xlim(0, 0.6)
        ax.set_xlabel("Relative $L_2$ error on genuine test (dimensionless)")
        ax.set_title(f"{dist.upper()} test set", fontsize=9)
        ax.grid(True, axis="x", alpha=0.3)
    fig.suptitle("Trained models (N=100, seed 11) vs trivial baselines; lower is better", fontsize=10)
    fig.tight_layout()
    out = PKG / "figures" / "audit_trivial_baselines.png"
    fig.savefig(out, dpi=140)
    plt.close(fig)
    return out


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--mode", choices=["smoke", "confirmatory"], default="confirmatory")
    p.add_argument("--pretrain-run", default=DEFAULT_PRETRAIN_RUN)
    args = p.parse_args()
    print(summarize_study3(args.mode, args.pretrain_run))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
